### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by studio3104** [studio3104/pytest-chalice#6]
- [x] Add type hintings
- [x] Write README
- [ ] Prepare Sphinx
- [ ] Enhance tests
- [x] Write a tiny example
- [ ] Write an example for overwriting the context
